### ISSUE TITLE
python mtk plstage --preloader=preloader_patched.bin  ........... Port - Device detected ￼ lpayload... PLTools - Successfully sent payload: C:\Users\ADMINPC\Desktop\amazonHD\mtkclient\mtkclient\payloads\mt6771_payload.bin Main - Connected to device, loading Main - Using custom preloader : preloader_patched.bin Traceback (most recent call last): File "C:\Users\ADMINPC\Desktop\amazonHD\mtkclient\mtk", line 943, in <module> mtk = Main(args).run(parser) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\ADMINPC\Desktop\amazonHD\mtkclient\mtkclient\Library\mtk_main.py", line 512, in run mtk.preloader.setreg_disablewatchdogtimer(mtk.config.hwcode) TypeError: Preloader.setreg_disablewatchdogtimer() missing 1 required positional argument: 'hwver'  C:\Users\ADMINPC\Desktop\amazonHD\mtkclient>

### ISSUE THREAD

**Issue by BASHEER-A** [bkerler/mtkclient#1044]
Old version is work without a problem, but new version of the tools. It's not work!![image](https://github.com/bkerler/mtkclient/assets/25770575/92388441-c5d6-48d8-8d55-0eee96685f5d)

**Comment by ColdWindScholar** [comment]
Fixed!

**Comment by ColdWindScholar** [comment]
Thanks for your issues!
