### ISSUE TITLE
Error when unlocking mt6789 (Helio G99) in V2.0.1

### ISSUE THREAD

**Issue by 10110000mh** [bkerler/mtkclient#1062]
i want to root the deice so i tried to open the bootloader
python mtk da seccfg unlock 
..........Port - Device detected :)
Preloader - 	CPU:			MT6789(MTK Helio G99)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
Preloader - HW code:			0x1208
Preloader - Target config:		0xe0
Preloader - 	SBC enabled:		False
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			8D7B39E4A65E332EC42CB64A85F9EA72
Preloader - SOC_ID:			35B1A5C908D4289E0E272AED496185D47D58E0E8A4C229EB931405EEADBB7D24
DaHandler - Device is unprotected.
DaHandler - Device is in BROM-Mode. Bypassing security.
DAXML - Uploading xflash stage 1 from MTK_DA_V6.bin
XmlFlashExt - Patching da2 ...
XmlFlashExt - Patched read_register / write_register
XmlFlashExt - Patched hash binding
Traceback (most recent call last):
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtk.py", line 980, in <module>
    mtk = Main(args).run(parser)
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/mtk_main.py", line 655, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/mtk_da_handler.py", line 155, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/mtk_daloader.py", line 298, in upload_da
    return self.da.upload_da()
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/xml/xml_lib.py", line 587, in upload_da
    if self.upload_da1():
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/xml/xml_lib.py", line 284, in upload_da1
    da1, da2 = self.patch_da(da1, da2)
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/xml/xml_lib.py", line 248, in patch_da
    da2 = self.xmlft.patch_da2(da2)
  File "/home/user/Desktop/mtkclient-2.0.1.freeze/mtkclient/Library/DA/xml/extension/v6.py", line 271, in patch_da2
    b"\xF0\x4D\x2D\xE9\x18\xB0\x8D\xE2\x82\xDF\x4D\xE2\x01\x60\xA0" +
TypeError: can't concat str to bytes

**Comment by Realme-10-4G** [comment]
hi friend, can you tell me how you managed to log into BROM-Mode

**Comment by 10110000mh** [comment]
i just used linux new version

**Comment by bkerler** [comment]
Please try commit [838b2ec](https://github.com/bkerler/mtkclient/commit/838b2ec0c226e39386d55bd50c64326ef30eb2fa)

**Comment by Boom-Hacker** [comment]
> Please try commit [838b2ec](https://github.com/bkerler/mtkclient/commit/838b2ec0c226e39386d55bd50c64326ef30eb2fa)

g99 is。supported？

**Comment by bkerler** [comment]
@Boom-Hacker yes, if sbc / daa / sla is disabled, which seems to be the case regarding the log.

**Comment by 10110000mh** [comment]
just tried in windows does not work will try in linux
