### ISSUE TITLE
MT8167 connection problem

### ISSUE THREAD

**Issue by hasan6034** [bkerler/mtkclient#1109]
......Preloader - 	CPU:			MT8167/MT8516/MT8362()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11005000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212c00
Preloader - 	Var1:			0xcc
Preloader - Disabling Watchdog...
Preloader - HW code:			0x8167
Preloader - Target config:		0xe0
Preloader - 	SBC enabled:		False
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xcb00
Preloader - 	SW Ver:			0x1
Preloader - ME_ID:			5B147049B660A4D79B83ECA3A6FD932C
Preloader - SOC_ID:			0000000000000000000000000000000000000000000000000000000000000000
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DeviceClass - USBError(32, 'Pipe error')
None

**Comment by R0rt1z2** [comment]
You should probably attach debug logs. Use the `--debugmode` option and pipe the output to some file.

**Comment by hasan6034** [comment]
I get this error when I boot it in debug mode

DeviceClass - USBError(32, 'Pipe error')
Traceback (most recent call last):
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtk.py", line 980, in <module>
    mtk = Main(args).run(parser)
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/mtk_main.py", line 655, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/mtk_da_handler.py", line 155, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/mtk_daloader.py", line 298, in upload_da
    return self.da.upload_da()
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/xflash/xflash_lib.py", line 1162, in upload_da
    self.set_checksum_level(0x0)
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/xflash/xflash_lib.py", line 235, in set_checksum_level
    return self.send_devctrl(self.Cmd.SET_CHECKSUM_LEVEL, param)
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/xflash/xflash_lib.py", line 187, in send_devctrl
    status[0] = self.status()
  File "/home/hasan/Desktop/mtkclient-main/mtkclient-main/mtkclient/Library/DA/xflash/xflash_lib.py", line 135, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes
