### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by fakerizz** [bkerler/mtkclient#1232]
.......Port - Device detected :)
Preloader -     CPU:                    MT6768(Helio P65/G85 k68v1)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0x25
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x707
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      20380B8B5FE1B11034DE18883B63AAF1
Preloader - SOC_ID:                     C710FEDA2A228B86F3F63E975E00DF0BAC93485010F7C9C2ECDBA82A530A768A
PLTools - Loading payload from mt6768_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\payloads\mt6768_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 9b01005930533235
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         Y0S256
DAXFlash - EMMC CID:        9b010059305332353600123729166afd
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x1000000
DAXFlash - EMMC USER Size:  0x3a3e000000
DAXFlash - DA-CODE      : 0x70E0
DAXFlash - DA Extensions successfully added
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate
sej - HACC init
sej - HACC run
sej - HACC terminate
usb_class - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtk", line 695, in <module>
    mtk = Main(args).run()
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\mtk_main.py", line 516, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\mtk_da_cmd.py", line 658, in handle_da_cmds
    v=mtk.daloader.seccfg(args.flag)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\mtk_daloader.py", line 225, in seccfg
    return self.xft.seccfg(lockflag)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\xflash_ext.py", line 514, in seccfg
    writedata = sc_new.create(sc_org=None, hwtype=hwtype, lockflag=lockflag, V3=V3)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\seccfg.py", line 67, in create
    enc_hash = self.hwc.sej.sej_sec_cfg_hw(dec_hash, True)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\hwcrypto_sej.py", line 480, in sej_sec_cfg_hw
    self.SEJ_Terminate()
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\hwcrypto_sej.py", line 323, in SEJ_Terminate
    self.reg.HACC_AKEY3 = 0
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\hwcrypto_sej.py", line 78, in __setattr__
    return self.write32(addr, value)
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\xflash_ext.py", line 293, in writeregister
    if not self.custom_writeregister(addr + pos, val):
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\xflash_ext.py", line 259, in custom_writeregister
    if self.cmd(XCmd.CUSTOM_WRITEREGISTER):
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\xflash_ext.py", line 224, in cmd
    status = self.status()
  File "C:\Users\Admin\Desktop\mtkclient-gui-20220121-x64\mtkclient\mtkclient\Library\mtk_daxflash.py", line 210, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**Comment by fakerizz** [comment]
issue #192  did not solve my problem

**Comment by bkerler** [comment]
Can you try using linux if the problem persists ?
