### ISSUE TITLE
Error while using "python mtk.py da seccfg unlock" or "python mtk.py da seccfg flag" device redmi k70 ultra

### ISSUE THREAD

**Issue by karlcctv** [bkerler/mtkclient#1244]
In version 2.0.1, when I was trying to use python mtk.py da seccfg unlock or python mtk.py da seccfg flag, python give an error:

Traceback (most recent call last):
  File "C:\Users\Karl\Desktop\mtkclient-2.0.1.freeze\mtk.py", line 980, in <module>
    mtk = Main(args).run(parser)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\Desktop\mtkclient-2.0.1.freeze\mtkclient\Library\mtk_main.py", line 655, in run
    mtk = da_handler.configure_da(mtk, preloader)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\Desktop\mtkclient-2.0.1.freeze\mtkclient\Library\DA\mtk_da_handler.py", line 86, in configure_da
    mtk.port.cdc.connected = mtk.port.cdc.connect()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\Desktop\mtkclient-2.0.1.freeze\mtkclient\Library\Connection\usblib.py", line 298, in connect
    for dev in devices:
               ^^^^^^^
  File "C:\Users\Karl\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 1292, in device_iter
    for dev in backend.enumerate_devices():
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 727, in enumerate_devices
    return _DevIterator(self.ctx)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 638, in __init__
    self.num_devs = _check(_lib.libusb_get_device_list(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karl\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error

This happen when I just type out the command, I tested that every command else are fine and usable.

**Comment by R0rt1z2** [comment]
Is UsbDk installed?

**Comment by karlcctv** [comment]
> Is UsbDk installed?

Yes, I also installed MTKdriver and Xiaomi Driver
