### ISSUE TITLE
shiboken2\libshiboken does not exist

### ISSUE THREAD

**Issue by nurabdullah94** [bkerler/mtkclient#204]
shiboken2\libshiboken does not exist

im sorry im newbie on python, i want to unlock bootloader mt6750 but after run "python mtk e metadata,userdata,md_udc" i got error :

Traceback (most recent call last):
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\mtkclient-main\mtk", line 5, in <module>
    from mtkclient.Library.mtk_main import Main, metamodes
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\mtkclient-main\mtkclient\Library\mtk_main.py", line 10, in <module>
    from mtkclient.Library.mtk import Mtk
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\mtkclient-main\mtkclient\Library\mtk.py", line 9, in <module>
    from mtkclient.Library.pltools import PLTools
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\mtkclient-main\mtkclient\Library\pltools.py", line 9, in <module>
    from mtkclient.Library.utils import LogBase, print_progress, logsetup
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\mtkclient-main\mtkclient\Library\utils.py", line 17, in <module>
    from PySide2.QtCore import Signal
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside2-5.15.2-py3.9-win-amd64.egg\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside2-5.15.2-py3.9-win-amd64.egg\PySide2\__init__.py", line 54, in _setupQtDirectories
    for dir in _additional_dll_directories(pyside_package_dir):
  File "C:\Users\Nur\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside2-5.15.2-py3.9-win-amd64.egg\PySide2\__init__.py", line 26, in _additional_dll_directories
    raise ImportError(shiboken2 + ' does not exist')
ImportError: C:\Users\Nur\AppData\Local\Programs\Python\Python39\lib\site-packages\shiboken2\libshiboken does not exist

i search shiboken2 on site-packages and got this folder "shiboken2-5.15.2-py3.9-win-amd64.egg"
and i try to make clone to change 1 folder to shiboken2 but still error, searching on internet and i still not solved this,

**Comment by nurabdullah94** [comment]
Solved 
open Lib\site-packagesshiboken2-5.15.2-py3.9-win-amd64.egg\shiboken2 Copy and Paste to outside Lib\site-packages\shiboken2 and make folder libshiboken

**Comment by bkerler** [comment]
Ok, closing this now.
