### ISSUE TITLE
rpmb read error

### ISSUE THREAD

**Issue by rebainoor** [bkerler/mtkclient#23]
D:\Github\mtkclient-1.4>python stage2 rpmb
Traceback (most recent call last):
  File "D:\Github\mtkclient-1.4\stage2", line 567, in <module>
    main()
  File "D:\Github\mtkclient-1.4\stage2", line 503, in main
    st2.rpmb(start, length, filename, args.reverse)
  File "D:\Github\mtkclient-1.4\stage2", line 304, in rpmb
    self.init_emmc()
  File "D:\Github\mtkclient-1.4\stage2", line 70, in init_emmc
    if unpack("<I", self.cdc.usbread(4))[0] == 0xD1D1D1D1:
struct.error: unpack requires a buffer of 4 bytes

**Comment by bkerler** [comment]
Hi,
for some devices, rpmb can only be read in preloader stage using plstage, for others only in brom mode using stage.
Please share more details about the used cpu, which mode you tried etc.
