### ISSUE TITLE
Dump full ROM to file command is failing.

### ISSUE THREAD

**Issue by nandbabai** [bkerler/mtkclient#257]
Hi Sir,

dump full ROM to file by command "python mtk rf flash.bin" is failing with below error. can you please look into it.

DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x59620
DAXFlash - DA Extensions successfully added
Traceback (most recent call last):
  File "E:\OPPO_RENO6_5G_Software\mtkclient-main\mtkclient-main\mtk", line 695, in <module>
    mtk = Main(args).run()
  File "E:\OPPO_RENO6_5G_Software\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_main.py", line 516, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "E:\OPPO_RENO6_5G_Software\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_da_cmd.py", line 551, in handle_da_cmds
    self.da_rf(filename=filename, parttype=parttype)
  File "E:\OPPO_RENO6_5G_Software\mtkclient-main\mtkclient-main\mtkclient\Library\mtk_da_cmd.py", line 243, in da_rf
    length = self.mtk.daloader.daconfig.flashsize[0]
TypeError: 'int' object is not subscriptable

**Comment by bkerler** [comment]
Hi, I will have a look into it ;)

**Comment by nandbabai** [comment]
@nandbabai 
@bkerler ,
can you please help on this case

**Comment by bkerler** [comment]
Sure, I will have a look at it ;)

**Comment by bkerler** [comment]
Issue is fixed with commit b30d65c

**Comment by nandbabai** [comment]
working as expected

**Comment by nandbabai** [comment]
working as expected hence closing.
