### ISSUE TITLE
Setting stage 2 config...

### ISSUE THREAD

**Issue by JayGDee** [bkerler/mtkclient#301]
Hi @bkerler .
I have an issue with the program not advancing past Setting stage 2 config.
I left it to run all night, thinking it may just take a while, but in the morning, it was still stuck there.
This is on a generic tablet Media Tek MT6592.
Here's the readout from the debug.
[17:40:59]: Status: Waiting for PreLoader VCOM, please connect mobile
[17:41:13]: 	CPU:			MT6592()
[17:41:13]: 	HW version:		0x0
[17:41:13]: 	WDT:			0x10007000
[17:41:13]: 	Uart:			0x11002000
[17:41:13]: 	Brom payload addr:	0x100a00
[17:41:13]: 	DA payload addr:	0x111000
[17:41:13]: 	CQ_DMA addr:		0x10212000
[17:41:13]: 	Var1:			0xa
[17:41:13]: Disabling Watchdog...
[17:41:13]: HW code:			0x6592
[17:41:13]: Target config:		0x0
[17:41:13]: 	SBC enabled:		False
[17:41:13]: 	SLA enabled:		False
[17:41:13]: 	DAA enabled:		False
[17:41:13]: 	SWJTAG enabled:		False
[17:41:13]: 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
[17:41:13]: 	Root cert required:	False
[17:41:13]: 	Mem read auth:		False
[17:41:13]: 	Mem write auth:		False
[17:41:13]: 	Cmd 0xC8 blocked:	False
[17:41:13]: Get Target info
[17:41:13]: BROM mode detected.
[17:41:13]: 	HW subcode:		0x8a00
[17:41:13]: 	HW Ver:			0xca00
[17:41:13]: 	SW Ver:			0x0
[17:41:13]: ME_ID:			5E3CFD31C57C96DF2A37399B8BCC7968
[17:41:15]: Device is unprotected.
[17:41:15]: Device is in BROM-Mode. Bypassing security.
[17:41:15]: Loading payload from mt6592_payload.bin, 0x258 bytes
[17:41:15]: Kamakiri / DA Run
[17:41:15]: Trying kamakiri2..
[17:41:15]: Done sending payload...
[17:41:16]: Successfully sent payload: C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\payloads\mt6592_payload.bin
[17:41:16]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
[17:41:17]: Uploading legacy da...
[17:41:17]: Uploading legacy stage 1 from MTK_AllInOne_DA_5.1420.bin
[17:41:17]: Jumping to 0x110000
[17:41:17]: Jumping to 0x110000: ok.
[17:41:17]: Got loader sync !
[17:41:17]: Reading nand info
[17:41:17]: NAND_INFO: 0xbc0
[17:41:17]: Reading emmc info
[17:41:17]: EMMC_INFO: 0x0
[17:41:17]: ACK: 04028a
[17:41:17]: Setting stage 2 config ...

Any ideas?

**Comment by JayGDee** [comment]
Also, when I stop the GUI, this is the readout I get from Powershell
Port - Device detected :)
legacyext
legacyext - [LIB]: ←[33mLegacy address check not patched.←[0m
None
Traceback (most recent call last):
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\gui\toolkit.py", line 113, in run
    self.function(self, self.parameters)
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtk_gui", line 87, in getDevInfo
    mtkClass = da_handler.configure_da(mtkClass, preloader=None)
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\Library\mtk_da_cmd.py", line 112, in configure_da
    if not mtk.daloader.upload_da(preloader=preloader):
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 202, in upload_da
    return self.da.upload_da()
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1067, in upload_da
    if self.upload():
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 1039, in upload
    self.set_stage2_config(self.config.hwcode)
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\Library\mtk_dalegacy.py", line 831, in set_stage2_config
    self.config.bmtsettings(self.config.hwcode)
  File "C:\Users\hanum\Desktop\MTK Tools\mtkclient-main\mtkclient\config\mtk_config.py", line 192, in bmtsettings
    if self.da.daconfig.flashtype == "emmc":
AttributeError: 'NoneType' object has no attribute 'daconfig'

**Comment by bkerler** [comment]
This issue could be caused by usb 3.0/usb 3.1. Please try to use a different usb port / hub, 2.0 one preferred. I don't know what causes this but for me, using a different usb 2.0 hub helped.
