### ISSUE TITLE
 python mtk reset error

### ISSUE THREAD

**Issue by nabicapar** [bkerler/mtkclient#56]
C:\Yeni klasör\mtkclient-main>python mtk reset

Traceback (most recent call last):
  File "mtk", line 1529, in <module>
    mtk = Main(args).run()
  File "mtk", line 624, in run
    info=mtk.daloader.reinit()
  File "C:\Yeni klasör\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 55, in reinit
    self.da.reinit()
  File "C:\Yeni klasör\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 960, in reinit
    self.sram, self.dram = self.get_ram_info()
  File "C:\Yeni klasör\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 540, in get_ram_info
    resp = self.send_devctrl(self.Cmd.GET_RAM_INFO)
  File "C:\Yeni klasör\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 271, in send_devctrl
    status[0] = self.status()
  File "C:\Yeni klasör\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 226, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**Comment by bkerler** [comment]
issue #42 does already exist.
