### ISSUE TITLE
[bug] 'NoneType' object has no attribute 'partition'

### ISSUE THREAD

**Issue by etmatrix** [bkerler/mtkclient#67]
I'm trying to read gpt partion on MT6739, but everytime I got this error

```
./mtk printgpt --debugmode

Main
Main - [LIB]: ./mtk printgpt --debugmode
usb_class
usb_class - [LIB]:   CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x43 (67 bytes)
   bNumInterfaces       :    0x2
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: CDC Communication =========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x2 CDC Communication
     bInterfaceSubClass :    0x2
     bInterfaceProtocol :    0x1
     iInterface         :    0x1 comm_if̦data_if̄Љ焄
      ENDPOINT 0x84: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x84 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x40 (64 bytes)
       bInterval        :    0x1
    INTERFACE 1: CDC Data ==================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x1
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :    0xa CDC Data
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x2 data_if̄Љ焄呪풅ཊꤛ漢䕄礤
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
Traceback (most recent call last):
  File "/opt/mediatek/mtkclient/./mtk", line 1529, in <module>
    mtk = Main(args).run()
  File "/opt/mtkclient/./mtk", line 672, in run
    data, guid_gpt = mtk.daloader.get_gpt(self.args)
  File "/opt/mtkclient/mtkclient/Library/mtk_daloader.py", line 115, in get_gpt
    data, guid_gpt = self.da.partition.get_gpt(int(arguments.gpt_num_part_entries),
AttributeError: 'NoneType' object has no attribute 'partition'
```
I executed it after a 

./mtk payload

```
Port - Device detected :)
Preloader - 	CPU:			MT6739/MT6731()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xb4
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xcb00
Preloader - 	SW Ver:			0x2
Preloader - Disabling Watchdog...
Preloader - HW code:			0x699
Preloader - Target config:		0x1
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - 	Mem write auth:		False
Preloader - 	Cmd 0xC8 blocked:	False
Mtk - We're not in bootrom, trying to crash da...
PLTools - Crashing da...
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
Preloader - Jumping to 0x0
USBError(19, 'No such device (it may have been disconnected)') <class 'usb.core.USBError'> 19
Preloader - Status: Waiting for PreLoader VCOM, please connect mobile
Port - Device detected :)
Preloader - 	CPU:			MT6739/MT6731()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0xb4
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xcb00
Preloader - 	SW Ver:			0x2
Preloader - Disabling Watchdog...
Preloader - HW code:			0x699
Preloader - Target config:		0xe1
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - ME_ID:			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Preloader - SOC_ID:			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PLTools - Loading payload from /opt/mediatek/mtkclient/mtkclient/payloads/mt6739_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /opt/mtkclient/mtkclient/payloads/mt6739_payload.bin
```
I have the same issue if I try to read boot partition with

./mtk r boot boot.bin

**Comment by bkerler** [comment]
that means that your device doesn't use gpt but hardcoded partitions. Can you give more details, which phone (vendor/model) and also upload full log via --debugmode (logs directory)

**Comment by etmatrix** [comment]
Thank you for your reply. Today I tested the latest commit and works. The issue is solved.
It's a nokia device which require a custom DA with SP Flash Tool.
Without payload I receive:

```
Main - Device is unprotected.
DAXFlash - Uploading stage 1...
Preloader
Preloader - [LIB]: upload_data failed with error: DAA_SIG_VERIFY_FAILED (0x7024)
Preloader
Preloader - [LIB]: Error on uploading da data
DAXFlash
DAXFlash - [LIB]: Error on sending DA.
Main
Main - [LIB]: Error uploading da
```

after mtk payload 

```
Main - [LIB]: Device is in BROM mode. No preloader given, trying to dump preloader from ram.
Successfully extracted preloader for this device to: /opt/mtkclient/mtkclient/Loader/Preloader/preloader_ant.bin
DAXFlash - Uploading stage 1...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - EMMC FWVer:      0x0
DAXFlash - EMMC ID:         FN62MB
DAXFlash - EMMC CID:        XXXXXXXXXXXXXXXXXXXXXXXXX
DAXFlash - EMMC Boot1 Size: 0x400000
DAXFlash - EMMC Boot2 Size: 0x400000
DAXFlash - EMMC GP1 Size:   0x0
DAXFlash - EMMC GP2 Size:   0x0
DAXFlash - EMMC GP3 Size:   0x0
DAXFlash - EMMC GP4 Size:   0x0
DAXFlash - EMMC RPMB Size:  0x80000
DAXFlash - EMMC USER Size:  0x1d2000000
DAXFlash - DA-CODE      : 0x999F0
DAXFlash - DA Extensions successfully added

GPT Table:
-------------
all entries of table
```

Payload works also without apply a patch to linux kernel, sure in README is written, I want confirm it. 

With the latest commit I have an execption on payload. Payload works, because after that operation I can read GPT and read flash, so it's not a real issue.

```
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /opt/mtkclient/mtkclient/payloads/mt6739_payload.bin
--- Logging error ---
Traceback (most recent call last):
  File "/opt/mtkclient/mtkclient/Library/usblib.py", line 417, in usbread
    extend(epr(resplen))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 983, in read
    ret = fn(
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 828, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/opt/mtkclient/mtkclient/Library/utils.py", line 347, in format
    return super(ColorFormatter, self).format(new_record, *args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/mtkclient/./mtk", line 1704, in <module>
    mtk = Main(args).run()
  File "/opt/mtkclient/./mtk", line 607, in run
    mtk = mtk.crasher()
  File "/opt/mtkclient/./mtk", line 208, in crasher
    plt.crash(crashmode)
  File "/opt/mtkclient/mtkclient/Library/pltools.py", line 179, in crash
    self.mtk.preloader.jump_da(0x0)
  File "/opt/mtkclient/mtkclient/Library/mtk_preloader.py", line 365, in jump_da
    if self.echo(self.Cmd.JUMP_DA.value):
  File "/opt/mtkclient/mtkclient/Library/Port.py", line 132, in echo
    tmp = self.usbread(len(val))
  File "/opt/mtkclient/mtkclient/Library/usblib.py", line 430, in usbread
    self.info(repr(e), type(e), e.errno)
Message: "USBError(5, 'Input/Output Error')"
Arguments: (<class 'usb.core.USBError'>, 5)
```

**Comment by etmatrix** [comment]
Well with last commit also this issue is solved.
Thank you
