### ISSUE TITLE
MT8127/MT3367 Fails to disable watchdog

### ISSUE THREAD

**Issue by iamnarky** [bkerler/mtkclient#724]
I ran into the same problem as https://github.com/bkerler/mtkclient/issues/180
So i tried tag 1.9 to see if it would work but unfortunately it did not.
I get the following error message on 1.9 and the main branch.
I ran the script on `Re LiveDVD`

```Port - Device detected :)
Preloader -     CPU:            MT8127/MT3367()
Preloader -     HW version:        0x0
Preloader -     WDT:            0x10007000
Preloader -     Uart:            0x11002000
Preloader -     Brom payload addr:    0x100a00
Preloader -     DA payload addr:    0x201000
Preloader -     Var1:            0xa
Preloader - Disabling Watchdog...
Traceback (most recent call last):
  File "/home/user/Desktop/mtkclient-1.9/mtk", line 782, in <module>
    mtk = Main(args).run(parser)
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_main.py", line 615, in run
    mtk = da_handler.configure_da(mtk, preloader)
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_da_cmd.py", line 78, in configure_da
    mtk.preloader.init()
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_preloader.py", line 192, in init
    self.setreg_disablewatchdogtimer(self.config.hwcode)  # D4
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_preloader.py", line 379, in setreg_disablewatchdogtimer
    res = self.write32(addr, value)
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_preloader.py", line 282, in write32
    return self.write(addr, dwords, 32)
  File "/home/user/Desktop/mtkclient-1.9/mtkclient/Library/mtk_preloader.py", line 260, in write
    if status > 0xFF: 
TypeError: '>' not supported between instances of 'list' and 'int'```

**Comment by crfw** [comment]
I am also running into this problem with the same device model.
