### ISSUE TITLE
Need Help: How to reflash gpt partitions?

### ISSUE THREAD

**Issue by RohitSurwase** [bkerler/mtkclient#800]
Whenever I try to write or read partition using mtkclient (Ex. python mtk printgpt) I am getting an error:
**struct.error: argument out of range**

**Detailed error:**
Traceback (most recent call last):
  File "C:\mtkclient\mtk", line 855, in <module>
    mtk = Main(args).run(parser)
  File "C:\mtkclient\mtkclient\Library\mtk_main.py", line 637, in run
    da_handler.handle_da_cmds(mtk, cmd, self.args)
  File "C:\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 607, in handle_da_cmds
    data, guid_gpt = mtk.daloader.get_gpt()
  File "C:\mtkclient\mtkclient\Library\DA\mtk_daloader.py", line 220, in get_gpt
    data, guid_gpt = self.da.partition.get_gpt(self.mtk.config.gpt_settings, parttype)
  File "C:\mtkclient\mtkclient\Library\partition.py", line 73, in get_gpt
    data = self.readflash(addr=0, length=sectors * self.config.pagesize, filename="",
  File "C:\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 764, in readflash
    if self.cmd_read_data(addr=addr, size=length, storage=storage, parttype=parttype):
  File "C:\mtkclient\mtkclient\Library\DA\xflash\xflash_lib.py", line 744, in cmd_read_data
    param = pack("<IIQQ", storage, parttype, addr, size)
struct.error: argument out of range

On similar error at https://github.com/bkerler/mtkclient/issues/333#issuecomment-1141788893
@bkerler commented - _That means that your gpt table likely is broken and needs to be reflashed._

But how to reflash gpt partitions?

Please help.

**Comment by bkerler** [comment]
Either using write flash or using repartition (whereas the latter isn't yet supported by mtkclient atm, use sp flash tool instead using mtk payload and uart setting in sp flash tool)
