### ISSUE TITLE
setuptools 69 breaks installation

### ISSUE THREAD

**Issue by tm-robinson** [bkerler/mtkclient#852]
Due to changes in setuptools, running setup.py build throws errors about pyproject.toml.

I was able to resolve this by downgrading setuptools to version 68.2.2 (pip install setuptools==68.2.2) as per this post: https://stackoverflow.com/questions/77523055/missingdynamic-license-defined-outside-of-pyproject-toml-is-ignored

The errors thrown were along the lines of:

```

(mtkclient) tom@lenovo:~/mtkclient$ python3 setup.py build
/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `description` defined outside of `pyproject.toml` is ignored.
!!

        ********************************************************************************
        The following seems to be defined outside of `pyproject.toml`:

        `description = 'Mediatek reverse engineering and flashing tools'`

        According to the spec (see the link below), however, setuptools CANNOT
        consider this value unless `description` is listed as `dynamic`.

        https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

        To prevent this problem, you can list `description` under `dynamic` or alternatively
        remove the `[project]` table from your file and rely entirely on other means of
        configuration.
        ********************************************************************************

!!
  _handle_missing_dynamic(dist, project_table)
/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `readme` defined outside of `pyproject.toml` is ignored.
!!

```

...

```


!!
  _handle_missing_dynamic(dist, project_table)
/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
  corresp(dist, value, root_dir)
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/dist.py", line 627, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
    return _apply(dist, config, filepath)
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
    _apply_project_table(dist, config, root_dir)
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
    corresp(dist, value, root_dir)
  File "/home/tom/mtkclient/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 163, in _long_description
    file = val.get("file") or []
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by bkerler** [comment]
This issue has been fixed with commit [30b5334](https://github.com/bkerler/mtkclient/commit/30b53348cc4ae73b88904bc96c33edff1f05e722). setup.py is considered depreciated.
