### ISSUE TITLE
Read Rpmb ok But Write rpmb Error 

### ISSUE THREAD

**Issue by mikoyoon** [bkerler/mtkclient#95]
write rpmb error logs...

python mtk xflash  rpmb w 
==================

.....Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      447C3B115D7F3702E8E38A02478AE33E
Preloader - SOC_ID:                     BB824356966D8C8EB427FAF754971889EF03291544ABB8DDE8B47A8AB4CD896D
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\payloads\mt6853_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2124.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AECMADAR
DAXFlash - UFS CID:      ad014839485131354145434d41444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ad014839485131354145434d41444152
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AECMADAR
DAXFlash - UFS CID:      ad014839485131354145434d41444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x969F0
DAXFlash - DA Extensions successfully added
None
xflashext
xflashext - [LIB]: ←[31mFilename has to be given for writing to rpmb←[0m

===================================================================================

next way ........
python xflash rpmb w --filename=rpmb.bin
=============================

..Port - Device detected :)
Preloader -     CPU:                    MT6853(Dimensity 720 5G)
Preloader -     HW version:             0x0
Preloader -     WDT:                    0x10007000
Preloader -     Uart:                   0x11002000
Preloader -     Brom payload addr:      0x100a00
Preloader -     DA payload addr:        0x201000
Preloader -     CQ_DMA addr:            0x10212000
Preloader -     Var1:                   0xa
Preloader - Disabling Watchdog...
Preloader - HW code:                    0x996
Preloader - Target config:              0xe7
Preloader -     SBC enabled:            True
Preloader -     SLA enabled:            True
Preloader -     DAA enabled:            True
Preloader -     SWJTAG enabled:         True
Preloader -     EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:  False
Preloader -     Root cert required:     False
Preloader -     Mem read auth:          True
Preloader -     Mem write auth:         True
Preloader -     Cmd 0xC8 blocked:       True
Preloader -     HW subcode:             0x8a00
Preloader -     HW Ver:                 0xca00
Preloader -     SW Ver:                 0x0
Preloader - ME_ID:                      447C3B115D7F3702E8E38A02478AE33E
Preloader - SOC_ID:                     BB824356966D8C8EB427FAF754971889EF03291544ABB8DDE8B47A8AB4CD896D
PLTools - Loading payload from mt6853_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\payloads\mt6853_payload.bin
Port - Device detected :)
Main - Device is protected.
Main - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading stage 1 from MTK_AllInOne_DA_5.2124.bin
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AECMADAR
DAXFlash - UFS CID:      ad014839485131354145434d41444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DRAM config needed for : ad014839485131354145434d41444152
DAXFlash - Sending emi data ...
DAXFlash - Sending emi data succeeded.
DAXFlash - Uploading stage 2...
DAXFlash - Successfully uploaded stage 2
DAXFlash - UFS FWVer:    0x0
DAXFlash - UFS Blocksize:0x1000
DAXFlash - UFS ID:       H9HQ15AECMADAR
DAXFlash - UFS CID:      ad014839485131354145434d41444152
DAXFlash - UFS LU0 Size: 0x1dcb000000
DAXFlash - UFS LU1 Size: 0x400000
DAXFlash - UFS LU2 Size: 0x400000
DAXFlash - DA-CODE      : 0x969F0
DAXFlash - DA Extensions successfully added
rpmb.bin
Traceback (most recent call last):
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtk", line 1709, in <module>
    mtk = Main(args).run()
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtk", line 1108, in run
    mtk.daloader.write_rpmb(args.filename)
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\Library\mtk_daloader.py", line 185, in write_rpmb
    return self.xft.write_rpmb(filename)
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\Library\xflash_ext.py", line 435, in write_rpmb
    if self.custom_rpmb_init():
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\Library\xflash_ext.py", line 377, in custom_rpmb_init
    status = self.status()
  File "C:\Users\Prestige14 A10SC\Desktop\GithubPj\mtk_blunlock\10_4_2021\mtkclient-main\mtkclient\Library\mtk_daxflash.py", line 211, in status
    magic, datatype, length = unpack("<III", hdr)
struct.error: unpack requires a buffer of 12 bytes

**Comment by KeuntaeShin** [comment]
After reversing da_x.bin,

At this point, CUSTOM_WRITE_RPMB is not well implemented in da_x.bin. The injected command for writing rpmb just calls mmc_rpmb_send_command(x) without forming "u8 *data_frame".

@bkerler : Isn't it?
