### ISSUE TITLE
OSError: Unable to find libfuse

### ISSUE THREAD

**Issue by jstaxxxx** [bkerler/mtkclient#995]
What on earth is wrong here?

Traceback (most recent call last):
  File "C:\users\jonas\mtkclient\mtk_gui", line 18, in <module>
    from mtkclient.Library.DA.mtk_da_handler import DA_handler
  File "C:\users\jonas\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 12, in <module>
    from mtkclient.Library.Filesystem.mtkdafs import MtkDaFS
  File "C:\users\jonas\mtkclient\mtkclient\Library\Filesystem\mtkdafs.py", line 1, in <module>
    from fuse import FuseOSError, Operations, LoggingMixIn
  File "C:\Users\Jonas\AppData\Local\Programs\Python\Python312\Lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse

**Comment by jstaxxxx** [comment]
I wish I searched before posting..
