### ISSUE TITLE
unable to find libfuse

### ISSUE THREAD

**Issue by naden01** [bkerler/mtkclient#996]
i get this error when write a command 

***C:\Users\Administrator\mtkclient>py mtk_gui
Traceback (most recent call last):
  File "C:\Users\Administrator\mtkclient\mtk_gui", line 18, in <module>
    from mtkclient.Library.DA.mtk_da_handler import DA_handler
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 12, in <module>
    from mtkclient.Library.Filesystem.mtkdafs import MtkDaFS
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\Filesystem\mtkdafs.py", line 1, in <module>
    from fuse import FuseOSError, Operations, LoggingMixIn
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse***

how to fix it?

**Comment by samuel1003** [comment]
It seems a new requierement missing, i am having same problem with latest commit
