### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by llqigithub** [bkerler/mtkclient#999]
所有py文件`Traceback (most recent call last):
  File "C:\Users\Administrator\mtkclient\mtk", line 5, in <module>
    from mtkclient.Library.mtk_main import Main, metamodes
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\mtk_main.py", line 18, in <module>
    from mtkclient.Library.DA.mtk_da_handler import DA_handler
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\DA\mtk_da_handler.py", line 12, in <module>
    from mtkclient.Library.Filesystem.mtkdafs import MtkDaFS
  File "C:\Users\Administrator\mtkclient\mtkclient\Library\Filesystem\mtkdafs.py", line 1, in <module>
    from fuse import FuseOSError, Operations, LoggingMixIn
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse`

**Comment by T0UB3S** [comment]
Could you solve it? I have the same problem in MTK Client

**Comment by ColdWindScholar** [comment]
Check #993
